import {
  ai as aiAWS,
  analytics as analyticsAWS,
  application as applicationAWS,
  compute as computeAWS,
  database as databaseAWS,
  iot as iotAWS,
  network as networkAWS,
  versionArray as versionAWSArray,
  other as otherAWS,
  security as securityAWS,
  storage as storageAWS,
  tools as toolsAWS,
} from './aws';

import {
  ai as aiGCP,
  analytics as analyticsGCP,
  application as applicationGCP,
  compute as computeGCP,
  versionArray as versionGCPArray,
  database as databaseGCP,
  iot as iotGCP,
  network as networkGCP,
  other as otherGCP,
  security as securityGCP,
  storage as storageGCP,
  tools as toolsGCP,
} from './gcp';

export const leftSideBarData = {
  aws: {
    icon: 's',
    versions: versionAWSArray,
    tabs: [
      computeAWS,
      networkAWS,
      storageAWS,
      databaseAWS,
      securityAWS,
      toolsAWS,
      aiAWS,
      analyticsAWS,
      applicationAWS,
      iotAWS,
      otherAWS,
    ],
  },
  gcp: {
    icon: 's',
    versions: versionGCPArray,
    tabs: [
      computeGCP,
      networkGCP,
      storageGCP,
      databaseGCP,
      securityGCP,
      toolsGCP,
      aiGCP,
      analyticsGCP,
      applicationGCP,
      iotGCP,
      otherGCP,
    ],
  },
};
