name: Feature request
description: Suggest a feature to improve InfraBoard
title: '[feature]: '
labels: [feature, infraboard, xerocodee, gssoc]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a feature for InfraBoard.
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an issue related to this feature request already exists.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Detailed Description
      description: Please provide a more detailed explanation of the feature.
  - type: textarea
    attributes:
      label: Use Cases and Benefits
      description: Describe specific use cases and potential benefits of this feature.
  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      options:
        - Low
        - Medium
        - High
  - type: markdown
    attributes:
      value: |
        If possible, please attach any relevant mockups, diagrams, or visual aids in a comment after submitting this issue.
