import { IoSettingsOutline } from 'react-icons/io5';

const tools = {
  title: 'Tools',
  icon: IoSettingsOutline,
  subTabs: [
    { title: 'Budgets' },
    { title: 'CE (Cost Explorer)' },
    { title: 'Clean Rooms' },
    { title: 'Cloud9' },
    { title: 'Cloud Control' },
    { title: 'CloudFormation' },
    { title: 'CloudTrail' },
    { title: 'CloudWatch' },
    { title: 'CodeArtifact' },
    { title: 'CodeBuild' },
    { title: 'CodeCatalyst' },
    { title: 'CodeCommit' },
    { title: 'CodeDeploy' },
    { title: 'CodeGuru' },
    { title: 'CodePipeline' },
    { title: 'CodeStar' },
    { title: 'Config' },
    { title: 'Control Tower' },
    { title: 'DataSync' },
    { title: 'FinSpace' },
    { title: 'Grafana' },
    { title: 'License Manager' },
    { title: 'MQ' },
    { title: 'OpsWorks' },
    { title: 'Organizations' },
    { title: 'Pinpoint' },
    { title: 'Prometheus (AMP)' },
    { title: 'Resource Explorer' },
    { title: 'Resource Groups' },
    { title: 'Service Catalog' },
    { title: 'Service Discovery' },
    { title: 'SES' },
    { title: 'SFN (Step Functions)' },
    { title: 'SNS' },
    { title: 'SWF Domain' },
    { title: 'Synthetics' },
    { title: 'Transcribe' },
    { title: 'Transfer' },
    { title: 'Verified Access' },
    { title: 'WorkLink' },
    { title: 'WorkSpaces' },
    { title: 'XRay' },
  ],
};

export default tools;
